### ISSUE TITLE
Export to the iOS App

### ISSUE THREAD

**Issue by kennyluk** [SCIInstitute/ImageVis3D#10]
We are able to use the Export to mobile feature to generate the i3m files. However, the documentation mention the presence of a data server to send the files to the iOS app. The links to the data server seems to be dead.

Where can one get the data server?

**Comment by schiewe** [comment]
GUI & command line IV3Dm data server versions can be downloaded here:

http://hpc.uni-due.de/data/IV3Dm/IV3DmDataServerGui-64-Mac.zip
http://hpc.uni-due.de/data/IV3Dm/IV3DmDataServerGui-64-Win.zip
http://hpc.uni-due.de/data/IV3Dm/IV3DmDataServerGui-64-Linux.zip
