### ISSUE TITLE
ImageVis3D installation problem

### ISSUE THREAD

**Issue by maheshs93** [SCIInstitute/ImageVis3D#5]
I am not able to generate, run batch file in script and it is not generating the needed QT libraries.

I am getting error 
 Performing moc on AboutDlg.h
  The system cannot find the path specified.

**Comment by tfogal** [comment]
Thanks for the ping, sorry you're having troubles.
If those Qt build scripts work, great; if not... sorry.  They're provided as a convenience, we don't want to get involved in Qt user support.
I would recommend a distribution-supplied or externally built Qt.

**Comment by maheshs93** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command "\bin\uic.exe "E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ImageVis3D\UI\UI\About.ui" -o "E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ImageVis3D\UI\UI\..\AutoGen\ui_About.h"" exited with code 1.	ImageVis3D	E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ui_files.targets	55	

In this line error is showing.the Auto gen folder is empty still 

 <UI
      Condition="'@(UI)' != '' and '%(UI.ExcludedFromBuild)' != 'true'"
      CommandLineTemplate="%(UI.CommandLineTemplate)"
      AdditionalOptions="%(UI.AdditionalOptions)"
      Inputs="%(UI.Identity)" />
