### ISSUE TITLE
Not able to generate files in Autogen file

### ISSUE THREAD

**Issue by maheshs93** [SCIInstitute/ImageVis3D#6]
the error i am getting due to Autogen folder is empty 
how to solve this error

E:\ImageVis3D-7\ImageVis3D\UI\AutoGen

Severity    Code    Description Project File    Line    Suppression State
Error   MSB3721 The command "\bin\uic.exe "E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ImageVis3D\UI\UI\About.ui" -o "E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ImageVis3D\UI\UI..\AutoGen\ui_About.h"" exited with code 1.  ImageVis3D  E:\Imgvis2008\ImageVis3D-7ed1d545821a3458a8617fc4c6a541dafd690caa\ui_files.targets  55

**Comment by tfogal** [comment]
Try setting the appropriate Qt environment variable: QTDIR32 or QTDIR64.  Set these so that e.g. $(QTDIR64)/bin/uic.exe is a valid command.

In the future, please include the command you executed as well.
