### ISSUE TITLE
ImageVis3D for iOS?

### ISSUE THREAD

**Issue by jhoongo** [SCIInstitute/ImageVis3D#7]
Hi,

Just quick question, I'm wondering if ImageVis3D would be available for iOS development.
I see some of the changes in regards to that, but is there any instruction or binary builds that would be available for mobile development?

It looks like really great product and would like to try few things out on some of my idea.

Thanks,

**Comment by jessdtate** [comment]
You can download imagevis3d mobile from the itunes store:  https://itunes.apple.com/us/app/imagevis3d-mobile-universal/id378071694?mt=8.

**Comment by jhoongo** [comment]
Hi,

I already downloaded the mobile application, but what I would like to do is to make something similar using imagevis3d like product, or just give it a try.  

Can ImageVis3D mobile be used for another application as library/SDK format? or is it solely for ImageVis3D's application?

**Comment by jessdtate** [comment]
I don't know how to get and work with the source code for imagevis3d mobile.  Maybe @butsonc, @gduffleu, or @tfogal could answer that?

**Comment by jhoongo** [comment]
Thanks @jessdtate if anyone of them could ping me here, that would be greatly appreciated.

**Comment by tfogal** [comment]
Last I knew, IV3D mobile was not open source.
ping @schiewe

**Comment by jhoongo** [comment]
@tfogal Is there any plan for open sourcing it? or is it possible to use this open-source IV3D library to make it work on mobile?

**Comment by schiewe** [comment]
Hi @jhoongo,

ImageVis3D Mobile (IV3Dm) sources and its enterprise features are only available to our collaborators. It is a separate project and implements a subset of the IV3D features for mobile devices but it is not based on the Tuvok sources.
There is also no IV3Dm library/SDK that could be easily used by another app.

If you are interested in a collaboration with us we would be happy to continue this conversation offline.
If you are just interested in looking at the sources you could check out the [duality project](https://github.com/SCIInstitute?q=duality). Its iOS front end is based on IV3Dm.

Cheers,
Alex

**Comment by jhoongo** [comment]
@schiewe Ok, thanks for the update :)
